### ISSUE TITLE
java.lang.IllegalArgumentException: URI is not absolute

### ISSUE THREAD

**Issue by ShravanReddy80** [Axway-API-Management-Plus/odata-routing-policy#1]
I followed the steps listed in https://github.com/Axway-API-Management-Plus/odata-routing-policy. 

- Used the MS Converter to convert the API.
- Created and deployed the routing policy.
- On-boarded the API.

When I test the Tripin API, I see the attached errors.

1)  com.vordel.apiportal.runtime.broker.CORSException: 'Origin' header not present. Terminating CORS processing.
2) java.lang.IllegalArgumentException: URI is not absolute

Any help would be appreciated.
[IAEerror.log](https://github.com/Axway-API-Management-Plus/odata-routing-policy/files/1925514/IAEerror.log)

**Comment by cwiechmann** [comment]
Thanks for the feedback!

I do see, based on the log you sent, that the generated destination URL is valid. 
`Generated destinationURL: http://services.odata.org/V4/(S(cnbm44wtbc1v5bgrlek5lpcc))/TripPinServiceRW/Airlines('AA')/Name`

So, I believe it has nothing to do with the URL itself, but instead with how the "Connect to URL" filter, which is part of your routing policy is configured.
I assume, that the filter is configured to the default attribute: `${http.request.uri}`, which resolves to null and leads to the error. 
If yes, could you please change it to "`${destinationURL}`". It must look like this:
![image](https://user-images.githubusercontent.com/16292002/38983228-268581c2-43c4-11e8-89bd-c5f60a676d37.png)

I'll make this requirement more clear in the readme.

Please let me know, if this helps.

PS: The CORS-Exception isn't really an error. The exception is only logged on DEBUG, so can ignore it.
