### ISSUE TITLE
[Feature] Create a ZIP-Package when releasing

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/odata-routing-policy#16]
**Is your feature request related to a problem? Please describe.**
Currently a user has to download the binary and all libs manually and has to guess, that everything must be place in the same directory.

**Describe the solution you'd like**
When releasing the OData-Converter we should package everything into a release package instead of having all artifacts separated:
![image](https://user-images.githubusercontent.com/16292002/136909718-09e876aa-7ac0-41a5-ab8c-97134508a851.png)

That release package should also contain the Policy-Fragment. The ultimate goal is to create a Release based on the GitHub-Release feature, which Kicks-Off a GitHub-Action, which automatically creates & upload the ZIP-Archive to the release package. Here is an example: https://github.com/Axway-API-Management-Plus/apigateway-openlogging-elk/blob/develop/.github/workflows/release-axway-elk-apim.yml

**Comment by rathnapandi** [comment]
All release files are bundled as zip and released during pipeline execution.
