### ISSUE TITLE
connectivity with backend service failing

### ISSUE THREAD

**Issue by ShravanReddy80** [Axway-API-Management-Plus/odata-routing-policy#2]
Hi,

When I use the policy, I am getting a **'transient failure connecting to remote: services.odata.org:80: connection failed: no usable address for service 80'** error. Please help me out with this.

Please find attached the screenshots and the logs.

---- The mainRoutingPolicy screenshots Begin -----

![1-mainroutingpolicy](https://user-images.githubusercontent.com/9274300/39532376-56ed6ebe-4df2-11e8-9aba-fda27ce9bc37.png)

![2-starttrace](https://user-images.githubusercontent.com/9274300/39532377-56faf6d8-4df2-11e8-90df-f4df26096644.png)

![3-odatarouting](https://user-images.githubusercontent.com/9274300/39532378-570b99fc-4df2-11e8-9f91-6e8ce8e06def.png)

![4-odataroutingpolicyscriptwithnochanges](https://user-images.githubusercontent.com/9274300/39532379-57195cd6-4df2-11e8-8eb1-4a95e7a94753.png)

![5-destinationtracer](https://user-images.githubusercontent.com/9274300/39532381-572fad10-4df2-11e8-843c-45f9a18ee393.png)

![6-connecttobackend](https://user-images.githubusercontent.com/9274300/39532375-56dd419c-4df2-11e8-90b8-262eaa40e980.png)

---- The mainRoutingPolicy screenshots End -----

----The APIM GW Request-Response screenshot and logs Begin -----
![req-resp](https://user-images.githubusercontent.com/9274300/39532472-81d06406-4df2-11e8-94bd-06f25a5c53bc.png)

The logs::: [req-resp.txt](https://github.com/Axway-API-Management-Plus/odata-routing-policy/files/1967872/req-resp.txt) 
The failure logs start at line number 644.

----The APIM GW Request-Response screenshot and logs End-----

----External REST client call to the service endpoint without the asterisk works Begin -----
When I called the odata service without the asterisk, the call worked and I got the below response.
![restcallwithoutasterisk](https://user-images.githubusercontent.com/9274300/39532890-55cbf1d0-4df3-11e8-812c-670f224c3b51.png)

----External REST client call to the service endpoint without the asterisk works End-----

**Comment by cwiechmann** [comment]
Can you please change the FE-API Path: 
From
/V4/(S(bwlyi5zyfdifrulnwfpj2f4u))/TripPinServiceRW/Airlines*
to:
/V4/TripPinServiceRW/Airlines*

And let me know, if this solved the problem? Perhaps the script doing the OData-Routing has issues with that. I tested it with exactly this FE-API-Path.

**Comment by cwiechmann** [comment]
Note: I'm really wondering about these log-messages:
```
get connection to host services.odata.org port 80 scheme http
no address for name services.odata.org, port 80: Name or service not known
transient failure connecting to remote: services.odata.org:80: connection failed: no usable address for service 80
```
Because they are pretty standard and logged, when the API-Gateway subsystem can't resolve the given hostname. Could you please make sure, that the API-Gateway server operating system can really resolve to services.odata.org?

**Comment by cwiechmann** [comment]
@ShravanReddy80, I have updated the Scripting-Filter slightly, as I have realized, that the issue appears when using the Try-It function in API-Manager/API-Portal.
When calling the endpoints that way, the "*" is included in the HTTP-Request and forwarded to the OData-Service, which returns you an error.
Even that is not a typical OData-Request, I understand that Try-It should work, so I improved this by removing the "*".

**Comment by cwiechmann** [comment]
@ShravanReddy80, hmm. The issue is the "*" at the end of the request. I assume you are using the API-Manager Try-It function, because this is using the registered API as it is (including the "*"). 
I have changed the policy in a way to remove this "*", but it seems not to work on your side, because it's send to the OData-Service, but it shouldn't. Not sure why!

Can you please try a request using an external program like CURL or Postman?
curl -k https://<apigateway>:8065/V4/TripPinServiceRW/Airlines

On my side this one is working as well:
curl -k https://<apigateway>:8065/V4/TripPinServiceRW/Airlines*

**Comment by ShravanReddy80** [comment]
@cwiechmann , It seems to have been a case of my deployment being overridden by someone else's deployment. I tested it now and its working fine. Thank you so much for helping me out with this.
