### ISSUE TITLE
[Help] * really needed

### ISSUE THREAD

**Issue by hongzhi0123** [Axway-API-Management-Plus/odata-routing-policy#22]
It is mentioned in the documentation, that Configured API-Methods must end with *. 
We imported swagger where API-Methods don't contain *. It works also.
Is the * really needed?

**Comment by rathnapandi** [comment]
Hi Hongzhi Zhang, 
The character * is not needed.  We added it for better readability. 

Thanks
Rathna

**Comment by rathnapandi** [comment]
Hi Hongzhi Zhang, 
The character * is not needed.  We added it for better readability. 

Thanks
Rathna

**Comment by hongzhi0123** [comment]
Hi Rathna,
I found comments in other thread that the * is still necessary for some special cases.
Could you please confirm if it could be a problem without the char *. in the cases described in this comment?
https://github.com/Axway-API-Management-Plus/odata-routing-policy/issues/19#issuecomment-943043519

Thanks
Hongzhi
