### ISSUE TITLE
4-part URI Failing (Unhandled Exception: System.UriFormatException: Invalid URI: The format of the URI could not be determined.)

### ISSUE THREAD

**Issue by kyle-kennedy** [Axway-API-Management-Plus/odata-routing-policy#3]
Attempting to generate a swagger file for a 4-part URI, e.g. http://server3.corp.na.com:8089/odata is failing with the following error: 

Unhandled Exception: System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at OData2Swagger.Program.Main(String[] args)

I have followed the instructions outlined in the README.md and have tested the correct functionality of the tool with the sample OData service URI provided (http://services.odata.org/V4/TripPinServiceRW). The issue only arises when attempting to convert a URI that has 4 period (.) separated parts.

**Comment by cwiechmann** [comment]
@rathnapandi, do you have any idea, why the format of the URI could not be determined? I mean it looks like a pretty standard URI?

**Comment by kyle-kennedy** [comment]
Hi @rathnapandi has there been any update on this topic? I am curious, because I am also seeing a similar error when attempting to convert for an OData service running locally, e.g. http://localhost:8080/odata

**Comment by kyle-kennedy** [comment]
After some more testing, it appears this may be an issue with including the port. Is there another way to specify the port for the service?

**Comment by rathnapandi** [comment]
@kyle-kennedy  can you share the response from odata service (http://localhost:8080/odata)? as we are reading metadata URL from a  JSON response element '@odata.context'.

**Comment by kyle-kennedy** [comment]
Hi @rathnapandi - the response looks as follows: 
<img width="779" alt="screen shot 2019-03-05 at 9 54 13 am" src="https://user-images.githubusercontent.com/42421321/53792794-c94eb400-3f2c-11e9-975f-e4cb2c8a4850.png">

**Comment by cwiechmann** [comment]
Hi @kyle-kennedy, I assume what Rathna meant was the "plain" output, which is returned, when accessing the endpoint directly. I mean for instance with a browser.

**Comment by kyle-kennedy** [comment]
hi @cwiechmann , apologies for the misunderstanding. This endpoint is providing a metadata description of the OData service, as is standard for many OData libraries. Regardless of whether or not this is correct, the issue still exists that users are unable to use the tool on a port other than 80, which is very restrictive.

**Comment by cwiechmann** [comment]
@kyle-kennedy, thanks and I agree!

@rathnapandi, so that would mean, we don't support any other port, than 80 with this tool? Can you confirm?

**Comment by kyle-kennedy** [comment]
<app:service xmlns:atom="http://www.w3.org/2005/Atom" xmlns:app="http://www.w3.org/2007/app" xmlns:metadata="http://docs.oasis-open.org/odata/ns/metadata" metadata:context="$metadata">
<app:workspace>
<atom:title>OData.Demo.Container</atom:title>
<app:collection href="Vehicles">
<atom:title>Vehicles</atom:title>
</app:collection>
</app:workspace>
</app:service>

**Comment by kyle-kennedy** [comment]
Here is an example of the XML OData service description from the endpoint of a sample app. As I understand, this is fairly standard.

**Comment by rathnapandi** [comment]
@cwiechmann  we do handle custom ports. 

@kyle-kennedy  seems you are not using odata version 4. can you please confirm? for odata v3 and lower use another exe file. 

D:\odata-routing-policy\converter\odata3\bin\Release>OdataSwaggerConverter.exe http://services.odata.org/V3/Northwind/Northwind.svc/$metadata name_of_swagger_file.json [http-basic-username] [http-basic-password]

**Comment by kyle-kennedy** [comment]
@rathnapandi thank you for responding. We are using Odata v4.0, as you can see when the content type  of the response is set to application/json (via Postman):

{
    "@odata.context": "$metadata",
    "value": [
        {
            "name": "Vehicles",
            "url": "Vehicles"
        }
    ]
}

Note that this is the same application and same endpoint. The browser will typically request XML-first, hence the different response above. The header of the response also confirms that this is OData v4.0: OData-Version: 4.0

**Comment by rathnapandi** [comment]
@kyle-kennedy the code looks for an URL from an element "@odata.context" but in your case we are getting as "$metadata"
Sample response from odata v4 service http://services.odata.org/V4/TripPinServiceRW returns URL 
`{"@odata.context":"http://services.odata.org/V4/(S(g4fvmcsykq24lxfdvu2tsefh))/TripPinServiceRW/$metadata","value":[{"name":"Photos","kind":"EntitySet","url":"Photos"},{"name":"People","kind":"EntitySet","url":"People"},{"name":"Airlines","kind":"EntitySet","url":"Airlines"},{"name":"Airports","kind":"EntitySet","url":"Airports"},{"name":"Me","kind":"Singleton",url":"Me"},{"name":"GetNearestAirport","kind":"FunctionImport","url":"GetNearestAirport"}]}`

As per microsoft ` The odata.context annotation returns the context URL (see [OData-Protocol]) for the payload. 
 This URL can be absolute or relative.`

[https://docs.microsoft.com/en-us/openspecs/odata_standards/ms-odatajson/1259ce6b-273d-4c01-9e79-48a0be630f39](url)

Either we need to fix the coverter code to handle relative URL  or  odata service should return fully qulaified URL as part the elment "@odata.context". 

Is it possible to change your odata service to return obsolute URL ? 

We will fix relateive URL issue as part of our next release.
